App\Domain\Aipd\Model\CriterePrincipeFondamental:
    properties:
        fichier:
            - File:
                  maxSize: 3072k
                  mimeTypes:
                      - image/jpeg
                      - image/png
                  mimeTypesMessage: 'aipd_validator.fichier.file'
                  groups: ['default']
