version: '3'

services:
###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]
###< symfony/mailer ###

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - ${PMA_PORT}:80
    environment:
      - PMA_HOST=db
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
      - UPLOAD_LIMIT=256M
    depends_on:
      - db
