<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20230808114234 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Correct question positions';
    }

    public function preUp(Schema $schema): void
    {
        parent::preUp($schema); // TODO: Change the autogenerated stub
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf('mysql' !== $this->connection->getDatabasePlatform()->getName(), 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('update aipd_analyse_question_conformite inner join conformite_traitement_question on aipd_analyse_question_conformite.question=conformite_traitement_question.question set aipd_analyse_question_conformite.position=conformite_traitement_question.position');
        $this->addSql('update aipd_modele_question_conformite inner join conformite_traitement_question on aipd_modele_question_conformite.question=conformite_traitement_question.question set aipd_modele_question_conformite.position=conformite_traitement_question.position');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf('mysql' !== $this->connection->getDatabasePlatform()->getName(), 'Migration can only be executed safely on \'mysql\'.');
    }
}
