App\Domain\Registry\Model\Request:
    denormalizationContext:
        groups: ['request_write']
    normalizationContext:
        groups: ['request_read']

    collectionOperations:
        get: ~
    itemOperations:
        get:
            security: 'is_granted("ROLE_ADMIN") or object.getCollectivity() == user.getCollectivity()'
