App\Domain\User\Model\Collectivity:
    attributes:
        name:
            groups: ['collectivity_read', 'request_read']
        user:
            groups: ['collectivity_read', 'request_read']
            max_depth: 1
